py_binary(
  name = "server",
  srcs = [
    "server.py", 
    "data/__init__.py", 
    "data/models.py", 
    "api/__init__.py", 
    "api/exceptions.py", 
    "api/routes.py", 
    "api/views.py",
    ],
)
